language: node_js
node_js:
  - 4.1.0
  - 4.0.0
  - 0.12
  - 0.11
  - 0.10
  - iojs-v3.0.0
  - iojs-v2.0.0
  - iojs-v1.0.0
sudo: false
script:
  - npm run test-ci
after_script:
  - codeclimate-test-reporter < ./coverage/lcov.info
addons:
  code_climate:
    repo_token:
      secure: "HZAB+YF25FPB8Qmlq7Ik/8TqYLBC0+XG8dEgZzDllrZnnA5q/DNDfRRJUNXJDWGtfDerJ5aGIjbcOI6S74OJP9xHfj5VyAXZXlC2T5f9WpQrXJeka62+hJg5A+RX3636603LsbVuohZrorPOFn4A8eexsAIBR/iSv8wUN5vRYgwW1EIGpXuspgsslNMg7sKGiEkrrbBQrHloUYFR8xZPPKVYja0XbxQaYBwF/HGy5ne2+S4/pR8aQYP1WnMLPaqb6qVbe5Qzwt8AoMaH6YvYYhQKlDn6qQSPd3PPVVlzF8QU0Sch+cEXq5RRbSW/JJ6D2ez0Gzkv4DZmbMqwVvAhIupGuBA8paGcnRsT5bUNMNv6/ysx0dQwbLP7v9jgVJsqYCiJxxLLnXj1pfvVBA+DJX2ZUcVSxHPww/I9lFGSDKS5nuNnCGN2SkBUVaQxYa4QT5Lo3ILMHdO8UJ6siUw4PeQypJAhEeLThqoi48uJHwR6kAZMcaOf7QUKwn4yuaeBY4A7NxyXnKmw6MOmva04D2i/8KxKnFFUUqWd1QHqz8HDUmloNPiA+tIQ73RPCLbOzVDj6tkJGw/9Wc4JXqg82LZMyoC5Ftugmis9wWH9tMUJRQHXW5fdJTqtMCh5RYliQL69FEjG7mrD7EptIVkaOS/NeluZA2hTgxwBQK2cJOQ="